blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/Kitware/trame/discussions
    about: Please use the discussions forum if you have questions or need help.