name: Docker
on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # To emulate other architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # For multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create month stamp
        run: echo "MONTH_STAMP=$(date +%Y-%m)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
            context: docker
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
                kitware/trame:latest
                kitware/trame:ubuntu-20.04-py39
                kitware/trame:${{ env.MONTH_STAMP }}

      - name: Build and push (glvnd)
        uses: docker/build-push-action@v2
        with:
            context: docker
            push: true
            build-args: BASE_IMAGE=nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04
            tags: |
                kitware/trame:glvnd
                kitware/trame:1.2-glvnd-runtime-ubuntu20.04-py39
                kitware/trame:glvnd_${{ env.MONTH_STAMP }}
