name: WebSite
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish WebSite
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Git Setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "sebastien.jourdain@kitware.com"
      - name: Publish WebSite
        if: github.ref == 'refs/heads/master'
        env:
          GIT_PUBLISH_URL: https://${{ secrets.GH_PUBLISH_CREDS }}@github.com/Kitware/trame.git
        run: npm run doc:publish
